<template>
  <div
    data-e2e-type="2fa-section"
    class="container h-100 pts-panel-body"
    :class="{ 'blur-loading-row': isLoading }"
  >
    <div class="row p-2" data-e2e-type="2fa-header">
      <div class="col col-12 pt-2 text-uppercase text-center mb-4">
        <h3>Two-Factor Authentication (2FA)</h3>
      </div>
      <div class="col col-12 d-flex align-items-center py-4">
        <input type="checkbox" date-e2e-type="checkbox-2fa" class="mr-2" v-model="state" :disabled="isSSOEnabled" />
        <label for="checkbox-2fa" class="mb-0">{{ stateLabel }}</label>
      </div>
      <div class="col col-12 pt-2">
        <p>
          Two-Factor Authentication or 2FA is an extra layer of protection
          used to ensure the security of online accounts beyond just a username
          and password. By enabling 2FA you will be asked for an
          authentication code when you sign in to your Big Language Solutions account.
          This process requires to set the app Google Auhtentificator on your
          mobile to retrieve the authentication code.
        </p>
      </div>
    </div>
    <div class="row p-2 align-items-center" v-show="isExpanded">
      <div class="col col-12 col-sm-6" data-e2e-type="2fa-setup-instruction">
        <h6 class="mb-4 text-center text-sm-left">
          Steps to set up Google Authentificator app on your mobile:
        </h6>
        <p>1) Open the Google Authentificator app on your phone.</p>
        <p>2) Inside the app, type the 'plus' icon to begin setup.</p>
        <p>
          3) Select the option 'Scan a barcode' and scan the following QRcode
          with your camera.
        </p>
      </div>
      <div class="col col-12 col-sm-6 text-center text-sm-left">
        <img v-if="dataURLRetieved" :src="hotpDataURL" />
      </div>
      <div class="col col-12">
        <h6>Test Google Authentificator App setup</h6>
        <p class="p-indent">
          Enter a six digit authentication code generated by Google
          Authentificator app and click on the "Verify" button to verify if you
          have set up Google Authentificator correctly.
        </p>
      </div>
      <div class="col-12 col-md-4 col-lg-3 ml-2">
        <form class="d-flex align-items-center" @submit.prevent="verifyHOTP">
          <input
            data-e2e-type="hotp-input"
            type="text"
            class="mr-2 form-control"
            aria-label="HOTP verification input"
            placeholder="6 digit code"
            v-model="hotp"/>
          <button
            data-e2e-type="hotp-verify-btn"
            class="btn btn-primary px-2"
            type="submit"
            :disabled="isLoading">
            Verify
          </button>
        </form>
      </div>
    </div>
  </div>
</template>
<script src="./settings.js" />
