const DEFAULT_QUALIFICATION_STATUS = 'Identifying';

export const defaultContactDetails = () => ({
  contactStatus: '',
  qualificationStatus: DEFAULT_QUALIFICATION_STATUS,
  salesRep: {
    _id: '',
    firstName: '',
    lastName: '',
    deleted: false,
    terminated: false,
  },
  linkedInUrl: '',
  mainPhone: {
    number: '',
    ext: '',
  },
  mailingAddress: {
    line1: '',
    line2: '',
    city: '',
    state: {
      name: '',
      code: '',
      country: {
        name: '',
        code: '',
      },
    },
    country: {
      name: '',
      code: '',
    },
    zip: '',
  },
  billingAddress: {
    line1: '',
    line2: '',
    city: '',
    state: {
      name: '',
      country: {
        name: '',
        code: '',
        country: '',
      },
    },
    country: {
      name: '',
      code: '',
    },
    zip: '',
  },
  billingEmail: '',
  leadSource: null,
});

export const defaultVendorDetails = () => ({
  type: 'V3',
  outlier: false,
  vendorCompany: '',
  ataCertified: false,
  escalated: false,
  turnOffOffers: false,
  competenceLevels: [],
  internalDepartments: [],
  minHours: 0,
  phoneNumber: '',
  address: {
    line1: '',
    line2: '',
    city: '',
    state: {
      name: '',
      country: {},
    },
    country: {},
    zip: '',
  },
  nationality: '',
  approvalMethod: '',
  hireDate: null,
  ofac: 'N/A',
  billingInformation: {
    paymentMethod: '',
    wtCountry: '',
    fixedCost: false,
    ptPayOrPayPal: '',
    priorityPayment: false,
    wtFeeWaived: false,
    billsOnHold: false,
    currency: '',
    flatRate: false,
    hasMonthlyBill: false,
    billCreationDay: null,
    flatRateAmount: 0,
    billingTerms: '',
    paymentFrequency: '',
    taxForm: [],
    taxId: '',
    form1099Type: '',
    form1099Box: '',
    billPaymentNotes: '',
    rates: [],
  },
  hiringDocuments: [],
  certifications: [],
  hipaa: false,
  gender: 'Not Selected',
  minimumHours: null,
  originCountry: null,
  isLawyer: false,
  isPracticing: false,
  isBarRegistered: false,
  registrationCountries: [],
  vendorStatus: 'Approved',
  billBalance: 0,
  debitMemoAvailable: 0,
  creditMemoAvailable: 0,
  totalBalance: 0,
});

export const defaultStaffDetails = () => ({
  outlier: false,
  competenceLevels: [],
  internalDepartments: [],
  remote: false,
  phoneNumber: '',
  jobTitle: '',
  approvalMethod: '',
  hireDate: null,
  ofac: 'N/A',
  comments: '',
  hiringDocuments: [],
});
